_target_: solver.GuidedSolver
device: "cuda"
seed: ${seed}
openai_model: qwen3.5-flash
openai_api_key_env: DASHSCOPE_API_KEY
openai_base_url: https://ws-qaz21f01ss4ma5ve.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1
openai_enable_thinking: true
subgoal_renderer:
  _target_: solver.PushTSubgoalRenderer
  resolution: ${eval.img_size}
